ffmeta/blueprints/api.py
import datetime
import os.path
import uuid

from flask import Blueprint, request, Response, jsonify, make_response, send_file, send_from_directory, render_template, current_app

from ffmeta.models.db import session
from ffmeta.models import Response, Variable, Umbrella, Topic
from ffmeta.utils import api_error, epochalypse_now, dedupe_varlist, search_db

bp = Blueprint('api', __name__)


@bp.route("/select")
def selectMetadata():
    # Get request data
    varname = request.args.get("varName")
    fieldname = request.args.get('fieldName', default=None)

    # Error out if varname not provided
    if not varname:
        return api_error(400, "Variable name not provided.")

    # Get variable data (abort if not valid)
    var = session.query(Variable).filter(Variable.name == varname).first()
    if not var:
        return api_error(400, "Invalid variable name.")
    var_data = var.serialize

    # Append topics
    topics = session.query(Topic).filter(Topic.name == varname).group_by(Topic.topic).all()
    umbrellas = session.query(Umbrella).filter(Umbrella.topic.in_([str(t.topic) for t in topics])).all()
    var_data["topics"] = [{"umbrella": str(u.umbrella), "topic": str(u.topic)} for u in umbrellas]

    # Append responses
    responses = session.query(Response).filter(Response.name == varname).group_by(Response.label).all()
    var_data["responses"] = {value: label for (value, label) in [(r.value, r.label) for r in responses]}

    # Error out if field name not valid
    if fieldname and fieldname not in var_data.keys():
        return api_error(400, "Invalid field name.")

    # Log query
    current_app.logger.info("{}\t{}\tselectMetadata\tname: {}\tfield: {}".format(epochalypse_now(), request.cookies.get("user_id"), varname, str(fieldname)))

    # Return only a single field if specified
    if not fieldname:
        rv = jsonify(var_data)
    else:
        result = {fieldname: var_data[fieldname]}
        rv = jsonify(result)

    resp = make_response(rv)

    # Set cookie data if not found
    if not request.cookies.get("user_id"):
        expire_date = datetime.datetime.now() + datetime.timedelta(days=90)
        g_uuid = str(uuid.uuid4())
        resp.set_cookie("user_id", g_uuid, expires=expire_date)

    return resp


@bp.route("/filter")
def filterMetadata():
    # Get request data
    fields = request.args.keys()

    # Error out if no fields provided
    if not fields:
        return api_error(400, "Fields to search not provided.")

    # Construct filter object
    found = []
    for field in fields:
        for value in request.args.getlist(field):
            found.extend(search_db(field, value))

    # Log query
    current_app.logger.info("{}\t{}\tfilterMetadata\tfilters: {}".format(epochalypse_now(), request.cookies.get("user_id"), list(request.args.items())))

    # Return list of matches
    if not found:
        rv = jsonify({"matches": []})
    else:
        varlist = dedupe_varlist(found)
        rv = jsonify({"matches": varlist})

    resp = make_response(rv)

    # Set cookie data if not found
    if not request.cookies.get("user_id"):
        expire_date = datetime.datetime.now() + datetime.timedelta(days=90)
        g_uuid = str(uuid.uuid4())
        resp.set_cookie("user_id", g_uuid, expires=expire_date)

    return resp


@bp.route("/search")
def searchMetadata():
    # Get request data
    querystr = request.args.get("query")
    fieldname = request.args.get('fieldName', default=None)

    # Error out if query or field not provided
    if not querystr:
        return api_error(400, "Query string not specified.")
    if not fieldname:
        return api_error(400, "Field name to search not specified.")

    # Search by table
    matches = search_db(fieldname, querystr)

    # Log query
    current_app.logger.info("{}\t{}\tsearchMetadata\tquery: {}\tfieldname: {}".format(epochalypse_now(), request.cookies.get("user_id"), querystr, fieldname))

    # Yield a list of variable names
    if not matches:
        rv = jsonify({"matches": []})
    else:
        rv = jsonify({"matches": matches})

    resp = make_response(rv)

    # Set cookie data if not found
    if not request.cookies.get("user_id"):
        expire_date = datetime.datetime.now() + datetime.timedelta(days=90)
        g_uuid = str(uuid.uuid4())
        resp.set_cookie("user_id", g_uuid, expires=expire_date)

    return resp

# Static pages #


# Favicon
@bp.route('/favicon.ico')
def favicon():
    return send_from_directory(os.path.join(current_app.root_path, 'static'),
                               'favicon.ico', mimetype='image/vnd.microsoft.icon')


# Full metadata file download
@bp.route('/get_metadata')
def metadata():
    # Log query
    current_app.logger.info("{}\t{}\tfull-file-download".format(epochalypse_now(), request.cookies.get("user_id")))
    return send_file(current_app.config["METADATA_FILE"], as_attachment=True)


# Feedback page
@bp.route("/feedback")
def feedback():
    return render_template('feedback.html')


# Landing page with API documentation
# Also, set a unique ID for this user
@bp.route("/")
def landing():
    resp = make_response(render_template('index.html'))

    # Set cookie data if not found
    if not request.cookies.get("user_id"):
        expire_date = datetime.datetime.now() + datetime.timedelta(days=90)
        g_uuid = str(uuid.uuid4())
        resp.set_cookie("user_id", g_uuid, expires=expire_date)

    # Log query
    current_app.logger.info("{}\t{}\thome".format(epochalypse_now(), request.cookies.get("user_id")))

    # Render index page
    return resp

ffmeta/templates/feedback.html
{% extends "ffmetadata.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSc-ip7IQafiGyp3A1LWq9Sx1_s8nbkvUVmdrrC2nqI9Y11jwQ/viewform?embedded=true" width="760" height="1000" frameborder="0" marginheight="0" marginwidth="0" align="center">Loading...</iframe>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

ffmeta/templates/ffmetadata.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>FFCWS Metadata | {% block title %}{% endblock %}</title>

        <!-- Styling -->
        <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}?1">
        <link rel="stylesheet" href="{{ url_for('static', filename='open-iconic.min.css') }}?1">
        <link rel="stylesheet" href="{{ url_for('static', filename='ff_metadata.css') }}?5">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato|Comfortaa">

        <!-- Scripts -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>

        <!-- Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-115020886-1"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'UA-115020886-1');
        </script>
    </head>

    <body>

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <img src="{{ url_for('static', filename='ffcws_banner.jpg') }}" class="img-responsive center-block" width="80%">
                </div>
                <div class="col-md-12">
                    <nav class="navbar navbar-default">
                      <div class="container-fluid">
                        <ul class="nav navbar-nav">
                            <a href="{{ url_for('api.landing') }}" class="center-block"><span class="navbar-brand"><span class="oi" data-glyph="code"></span>  FFCWS Metadata API</span></a>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li role="presentation"><a href="http://metadata.fragilefamilies.princeton.edu"><span class="oi" data-glyph="list-rich"></span>  Browse online</a></li>
                            <li role="presentation"><a href="{{ url_for('api.metadata') }}"><span class="oi" data-glyph="data-transfer-download"></span>  Download metadata</a></li>
                            <li role="presentation"><a href="{{ url_for('api.feedback') }}"><span class="oi" data-glyph="chat"></span>  Feedback</a></li>
                            <li role="presentation"><a href="http://fragilefamilies.princeton.edu/"><span class="oi" data-glyph="globe"></span>  About FFCWS</a></li>
                        </ul>
                      </div>
                    </nav>
                </div>
            </div>
        </div>

        <div class="mainblock">
            {% block body %}{% endblock %}
        </div>

    </body>

    <footer>
            {% block foot %}{% endblock %}
    </footer>

</html>

ffmeta/templates/index.html
{% extends "ffmetadata.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header"><h2>Fragile Families and Child Wellbeing Study</h2></div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <p class="lead">Metadata API</p>
                            <p>We provide three API endpoints:
                                <ul>
                                    <li><p>
                                        <code>select(varName, fieldName)</code><br/>
                                        &emsp;Returns metadata for variable <code>varName</code>.<br/>
                                        &emsp;(Optionally, returns only the field specified by <code>fieldName</code>.)<br/>
                                        &emsp;e.g. <code><a href="{{ url_for('api.selectMetadata') + '?varName=cm1relf' }}">GET /select?varName=cm1relf</a></code>

                                    </p></li>
                                    <li><p>
                                        <code>filter(*fieldNames)</code><br/>
                                        &emsp;Return a list of variables where <code>fieldName</code> matches the provided value.<br/>
                                        &emsp;e.g. <code><a href="{{ url_for('api.filterMetadata') + '?responses=sometimes' }}">GET /filter?responses=sometimes</a></code>
                                    </p></li>
                                    <li><p>
                                        <code>search(query, fieldName)</code><br/>
                                        &emsp;Return a list of variables where <code>query</code> is found in <code>fieldName</code>.<br/>
                                        &emsp;e.g. <code><a href="{{ url_for('api.searchMetadata') + '?query=age&fieldName=label' }}">GET /search?query=age&fieldName=label</a></code>
                                    </p></li>
                                </ul>
                        </div>
                        <div class="col-md-6">
                            <p class="lead">Other utilities for FFCWS data users</p>
                            <p>To browse variables interactively, click <em>Browse online</em>.</p>
                            <p>To download metadata for all variables as a CSV file, click <em>Download metadata</em>.</p>
                            <p>If you have any comments or ideas for how to improve the metadata or this API, click <em>Feedback</em>.</p>
                            <p>For more information on the Fragile Families and Child Wellbeing Study, click <em>About FFCWS</em>.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}